name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t niloyan/dierentuin:latest -f Dierentuin/Dockerfile .

    - name: Push Docker image
      run: docker push niloyan/dierentuin:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: actions/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up kubeconfig
      run: echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 -d > ~/.kube/config

    - name: Deploy to Kubernetes
      run: kubectl apply -f Dierentuin/deploy.yml
