name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Build and test Docker image
      run: docker build --target testrunner -t dierentuin:test -f Dierentuin/Dockerfile .

    - name: Build the Docker image for release
      run: docker build --target publish -t dierentuin:${{ github.ref_name }} -f Dierentuin/Dockerfile .

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push dierentuin:${{ github.ref_name }}
