name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Haalt de meest recente code van de main branch op

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        # Configureert Docker Buildx voor geavanceerde build-opties

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # Logt in op Docker Hub met de gegevens die als geheimen zijn opgeslagen in je GitHub repository

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: yourusername/yourimage:latest
        # Bouwt het Docker-image en pusht het naar Docker Hub onder de opgegeven tag

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Haalt de code opnieuw op voor gebruik in de deployment fase

      - name: Install kubectl
        run: bash ./scripts/install-kubectl.sh
        # Voert een shell script uit om kubectl te installeren, zorg dat dit script in je repo staat onder de map scripts

      - name: Apply Kubernetes Manifests
        run: kubectl apply -f ./k8s/deployment.yaml
        # Past de Kubernetes manifesten toe vanuit de gespecificeerde directory en bestand

