name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t dierentuin:${{ github.ref_name }} -f Dierentuin/Dockerfile .
    - name: Run Docker container
      run: docker run -d --name dierentuin_container dierentuin:${{ github.ref_name }}
    - name: Run tests
      run: docker exec dierentuin_container pytest Dierentuin/TestProject1
    - name: Cleanup
      run: docker rm -f dierentuin_container
